### ISSUE TITLE
requirements wrong versions

### ISSUE THREAD

**Issue by BDadmehr0** [minecraft-py/minecraft#43]
There are some dependencies with their versions in the requirements.txt file, but the game supports dependencies with other versions
For example, the pillow library that the game uses is version 10.0.0, but what it installs in the prerequisites is 10.0.1.

**Comment by zhengxyz123** [comment]
Thanks for your advice, I have fixed it in a [recent commit](https://github.com/minecraft-py/minecraft/commit/4daca2b9ec4acb08ba1f4e0486a575225cd0fcea).
